name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:

# ! Repo Project---------------------------------------------------------------------------------------
    - name: Assign issues to repo project
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/Andreasgdp/Inverted-Pendulum/projects/1'
